---
on:
  push:
    tags:
    - 'v*'
    - '!v*.pre*'

name: Create Release

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
    - name: Get version from tag
      id: tag_name
      shell: bash
      run: |
        echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v1
      with:
        version: ${{ steps.tag_name.outputs.current_version }}
        path: ./CHANGELOG.md
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GEM_RELEASE_GIT_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog_reader.outputs.log_entry }}
        draft: false
        prerelease: false
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"
    - name: Install yard
      run: gem install yard --no-document
    - name: Generate Documentation
      run: yard doc --output-dir doc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GEM_RELEASE_GIT_TOKEN }}
        external_repository: invoca/internal-docs
        publish_branch: main
        publish_dir: ./doc
        destination_dir: ${{ github.event.repository.name }}
        user_name: auto-doc[bot]
        user_email: auto-doc[bot]@users.noreply.github.com
